apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: .dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newName: .dkr.ecr.ap-northeast-1.amazonaws.com/demo-frontend
  newTag: abcdefg
- name: 671949607145.dkr.ecr.ap-northeast-1.amazonaws.com/
  newName: 671949607145.dkr.ecr.ap-northeast-1.amazonaws.com/
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
